version: 2

project_name: icetray

release:
  github:
    owner: jdbnet
    name: icetray
  extra_files:
    - glob: dist/icetray-linux-amd64
    - glob: dist/icetray-headless-linux-amd64
    - glob: dist/icetray-linux-arm64
    - glob: dist/icetray-headless-linux-arm64
    - glob: dist/icetray-windows-amd64.exe
    - glob: dist/icetray-windows-arm64.exe
    - glob: dist/icetray_*_*.deb

changelog:
  disable: true
