// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails application binding layer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metadata$0 from "./metadata/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddStream creates a new stream.
 */
export function AddStream(name: string, url: string): $CancellablePromise<$models.StreamView> {
    return $Call.ByID(142269684, name, url);
}

/**
 * GetImagePath returns the filesystem path for a stream image (for tray/debug).
 */
export function GetImagePath(filename: string): $CancellablePromise<string> {
    return $Call.ByID(3847422371, filename);
}

/**
 * GetNowPlaying returns the latest metadata snapshot.
 */
export function GetNowPlaying(): $CancellablePromise<metadata$0.NowPlaying> {
    return $Call.ByID(3484607849);
}

/**
 * GetPlaybackState returns current playback state.
 */
export function GetPlaybackState(): $CancellablePromise<$models.PlaybackState> {
    return $Call.ByID(1328019839);
}

/**
 * GetSettings returns app settings.
 */
export function GetSettings(): $CancellablePromise<$models.SettingsView> {
    return $Call.ByID(2554697378);
}

/**
 * GetStreams returns all saved streams with optional embedded image data.
 */
export function GetStreams(): $CancellablePromise<$models.StreamView[] | null> {
    return $Call.ByID(929629524);
}

/**
 * Pause pauses playback.
 */
export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(1037007909);
}

/**
 * PickStreamImage opens a file dialog and saves artwork for a stream.
 */
export function PickStreamImage(streamID: string): $CancellablePromise<$models.StreamView> {
    return $Call.ByID(3813822493, streamID);
}

/**
 * PlayLastStream plays the last selected stream if any.
 */
export function PlayLastStream(): $CancellablePromise<void> {
    return $Call.ByID(37984595);
}

/**
 * PlayStream starts playback for a stream by ID.
 */
export function PlayStream(id: string): $CancellablePromise<void> {
    return $Call.ByID(3144545219, id);
}

/**
 * QuitApp exits the application.
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(3730234565);
}

/**
 * RemoveStream deletes a stream and its artwork.
 */
export function RemoveStream(id: string): $CancellablePromise<void> {
    return $Call.ByID(2772669893, id);
}

/**
 * ReorderStreams saves a new stream list order.
 */
export function ReorderStreams(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1402949913, ids);
}

/**
 * Resume resumes playback.
 */
export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(2476070530);
}

/**
 * SetAutoplay toggles autoplay on startup.
 */
export function SetAutoplay(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3697473762, enabled);
}

/**
 * SetLaunchMinimized toggles whether the player window starts hidden (desktop tray only).
 */
export function SetLaunchMinimized(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(562261216, enabled);
}

/**
 * SetLaunchOnLogin toggles launch on login.
 */
export function SetLaunchOnLogin(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1469259994, enabled);
}

/**
 * SetVolume sets volume 0-100. Android uses the device volume only.
 */
export function SetVolume(vol: number): $CancellablePromise<void> {
    return $Call.ByID(1458705221, vol);
}

/**
 * ShowPlayer shows and focuses the main window.
 */
export function ShowPlayer(): $CancellablePromise<void> {
    return $Call.ByID(2332747161);
}

/**
 * Shutdown cleans up on application exit.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(2987688963);
}

/**
 * Stop stops playback.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(4158193117);
}

/**
 * TrayPause handles pause from the system tray.
 */
export function TrayPause(): $CancellablePromise<void> {
    return $Call.ByID(1552423181);
}

/**
 * TrayPlay handles play from the system tray.
 */
export function TrayPlay(): $CancellablePromise<void> {
    return $Call.ByID(1631382755);
}

/**
 * TrayStop handles stop from the system tray.
 */
export function TrayStop(): $CancellablePromise<void> {
    return $Call.ByID(1774468965);
}

/**
 * UpdateStream updates stream name and URL.
 */
export function UpdateStream(id: string, name: string, url: string): $CancellablePromise<void> {
    return $Call.ByID(2573398884, id, name, url);
}
