// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlaybackState describes current playback.
 */
export interface PlaybackState {
    "playing": boolean;
    "paused": boolean;
    "streamId": string;
    "volume": number;
}

/**
 * SettingsView exposes app settings to the frontend.
 */
export interface SettingsView {
    "autoplay": boolean;
    "launchOnLogin": boolean;
    "launchMinimized": boolean;
    "volume": number;
    "desktop": boolean;
}

/**
 * StreamView is a stream exposed to the frontend.
 */
export interface StreamView {
    "id": string;
    "name": string;
    "url": string;
    "image"?: string;
    "imageData"?: string;
}
