// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NowPlaying holds track metadata from an Icecast server when available.
 */
export interface NowPlaying {
    "station": string;
    "title": string;
    "genre"?: string;
    "listeners"?: number;
}
